hash-format = "sha256"

[[files]]
file = "config/DistantHorizons.toml"
hash = "6ab8a99d80fcba550f329ce49f52b86b8fdf9e3b9d4b78a936220aa2aecd53be"

[[files]]
file = "config/EasyAuth/extended.conf"
hash = "9e7d0bf997c396baba88dc1ed71eb849e805bbd2dbf226eb1c33660804b5b37d"

[[files]]
file = "config/EasyAuth/main.conf"
hash = "9e80f8ff3ad549f2e71e3e0eda6910bf5d03bc017ff27a892b75d231ea047825"

[[files]]
file = "config/EasyAuth/storage.conf"
hash = "f48492909742061009b84298893d2c6dde55301ec3447da24bc52d4e9e89a1cf"

[[files]]
file = "config/EasyAuth/technical.conf"
hash = "ad1e69d75a75503779ac12af9ec7462c4fdfe2f8087504b1b08fe9f108338471"

[[files]]
file = "config/EasyAuth/translation.conf"
hash = "1ce6eb309fc914916d8fb296401d2694a2bc968b8a4c4170d8f4e2e43b7fef27"

[[files]]
file = "config/antixray.toml"
hash = "6b365812291fb635b7e2dea096f52bed88e1d7ada9656bdda1dbc2ec759a3e94"

[[files]]
file = "config/bluemap/core.conf"
hash = "8d1a979cf19e179a7ea76bb4092abb5d667489641cfde9e461088bda845db7c1"

[[files]]
file = "config/bluemap/maps/world.conf"
hash = "0d2931420deaee1cc087418a1b4e0663b5805d27d28b06eca5bb1720079dc485"

[[files]]
file = "config/bluemap/maps/world_the_end.conf"
hash = "f21253d3e9787b2f1a16f7c20770e8c15f2d5d35fd3c80489a957e7d6f60e91d"

[[files]]
file = "config/bluemap/maps/world_the_nether.conf"
hash = "530a8f123ccdd9a4805f8ef72ba3823e68e2c378cf49c97705bb6867ca371c95"

[[files]]
file = "config/bluemap/plugin.conf"
hash = "1bed9d05abfad0a839026f30bdef039e3a93f5af6d72f574a7e57b8917a32e6d"

[[files]]
file = "config/bluemap/storages/file.conf"
hash = "f99f612f071326c55c65ba6fa5bef73978b286fdafcd350d56aa38c35fc4f120"

[[files]]
file = "config/bluemap/storages/sql.conf"
hash = "ecea74225bdf8911433354f7fa3627b49e666c9b5024c9a8e5fc45eebddfc620"

[[files]]
file = "config/bluemap/webapp.conf"
hash = "34e793cce96f42471e391b1780d90b37be590bccc5a0a596eba28e4a05416a28"

[[files]]
file = "config/bluemap/webserver.conf"
hash = "a0a09b7d4ae8fbd0c0431131b99e777f412fcc5e6948821da411c2863a0fadd4"

[[files]]
file = "config/c2me.toml"
hash = "90f7abeee79ce071a1bdabfa3e66c494eb874eec3226f3a1e5640068e761ab86"

[[files]]
file = "config/chunky/config.json"
hash = "c7384a22595488f79f3125b22cc175eb729267267807a084479419349797abc8"

[[files]]
file = "config/ferritecore.mixin.properties"
hash = "3cc3011619f098fda6ad213a7c4d1468802ff827591a5917c2b7bf3150bfb2ea"

[[files]]
file = "config/forgivingvoid-common.toml"
hash = "e60d2e921f033f4603d37927fb70544150a7702af4d23a1cd49d459814c3c42d"

[[files]]
file = "config/image2map.json"
hash = "017fcc31d5228472e9c4e42054f28df39c2bc11010ec6ae035d7af1d1b7e1eb3"

[[files]]
file = "config/lithium.properties"
hash = "6cf6f83720071fd1657c8e79b357caf68d40f410ae123e5f922483eb1d1d25be"

[[files]]
file = "config/luckperms/luckperms.conf"
hash = "e78ae10450e5d0386f1e529f13e5895be549b5635f765b4af696050bb91a7c01"

[[files]]
file = "config/luckperms/translations/repository/ar_SA.properties"
hash = "bf8293312a11f0b2cd298a81fe17a51ca72c251b604d581a372c45c7360504eb"

[[files]]
file = "config/luckperms/translations/repository/bg_BG.properties"
hash = "06d5a4506b42a80e4bbf4d61801a2166613a441eb9418aa73a3c84e13be3c74a"

[[files]]
file = "config/luckperms/translations/repository/cs_CZ.properties"
hash = "c3706f0c9b8dcc15b839dbc28c30abbaa549d429508ce2788d0eb2ed189c6a89"

[[files]]
file = "config/luckperms/translations/repository/da_DK.properties"
hash = "25df30b219ddf973f39741ccfb112a3bbcb23b19317f854742c204ba3cd14b66"

[[files]]
file = "config/luckperms/translations/repository/de_DE.properties"
hash = "181b26352e6d8731b6d6a96dc188d6283d21e0731209b8e9e0b6fb3f5c455969"

[[files]]
file = "config/luckperms/translations/repository/el_GR.properties"
hash = "500a58cccf9935cf0014f9d0c6c738aee2fb7ada382942620c71a12fafe9ee84"

[[files]]
file = "config/luckperms/translations/repository/en_PT.properties"
hash = "b4e30ccde47e435249520b1edcab5c771b5263662f1b61caf6fb8d8ef090d343"

[[files]]
file = "config/luckperms/translations/repository/es_ES.properties"
hash = "0e88d189b5d075036d4c7d39baf2dc7debec4bc11bea7b524a43e2a84fdef8e0"

[[files]]
file = "config/luckperms/translations/repository/fa_IR.properties"
hash = "830623f0017d2bbc92a4eab17fb2c89e8f8c63213da92864c715a04c6af5ffc5"

[[files]]
file = "config/luckperms/translations/repository/fi_FI.properties"
hash = "a7b6f2ea67bb2ff88708eeb1bfc6ff0e2bf0ab5e918e4a787f05f648d195660d"

[[files]]
file = "config/luckperms/translations/repository/fil_PH.properties"
hash = "b7d79b5b192664855fbf3cdedf55b1a93a6a7b7dee17eeee28cbf74000852ce2"

[[files]]
file = "config/luckperms/translations/repository/fr_FR.properties"
hash = "78bec8b2294f9fd2a6a958d7153057064bc7f6bf99aeae4889d73bb844ab30f0"

[[files]]
file = "config/luckperms/translations/repository/he_IL.properties"
hash = "0b3836e270dcae860f7851ca511c02ba231ad422c0d35b42499bdc657126c1f0"

[[files]]
file = "config/luckperms/translations/repository/hi_IN.properties"
hash = "e2f23be431a0ba843bd02b1c1acd7ecc8c227170619a80d3faad08c7040f7292"

[[files]]
file = "config/luckperms/translations/repository/hu_HU.properties"
hash = "6b26d964931d5be3890bbea50ed7d8ef73a6bed172bb64422bf6349e08d90320"

[[files]]
file = "config/luckperms/translations/repository/id_ID.properties"
hash = "1abc861f060461b73a018006c33edbab54a5d19be5ee178f86fee50d42dca0a3"

[[files]]
file = "config/luckperms/translations/repository/it_IT.properties"
hash = "73ba306112d85a6e88f3d689b0af7de67ee7397748965f49a7970c6b1d311913"

[[files]]
file = "config/luckperms/translations/repository/ja_JP.properties"
hash = "b9e839bae812811dc3f44ff3d8086f0a86ad45e56223fd6e88e7723ffa7c1822"

[[files]]
file = "config/luckperms/translations/repository/ka_GE.properties"
hash = "2c0ad2e6de804c6ae13b4e5fb7c0c387a16e04710fc5a87f02e0aa09f4ba7383"

[[files]]
file = "config/luckperms/translations/repository/ko_KR.properties"
hash = "35051dd4dab93215a6d623af11f7c273169617157ab260baa27addd69f6e1651"

[[files]]
file = "config/luckperms/translations/repository/nl_NL.properties"
hash = "7674ff756a3c3aae7c450dd88d3bf5e446757bc1dc6820edf77f5645927fe080"

[[files]]
file = "config/luckperms/translations/repository/no_NO.properties"
hash = "902c97ce770205af9a0ef3cb04927b187a607a4cbd0bf460457065ca0e62f949"

[[files]]
file = "config/luckperms/translations/repository/pl_PL.properties"
hash = "831f701155a953fa14c1967b84e30893eeacf4215af0cc7c4170e1c84cf66efe"

[[files]]
file = "config/luckperms/translations/repository/pt_BR.properties"
hash = "4ee4f3669e790dec7ecf62e2b6d0350cdd2fd41838925c7c7edf0746e588b755"

[[files]]
file = "config/luckperms/translations/repository/ro_RO.properties"
hash = "b0954c2b060b164d55eb5a143277dfd00cfd47ca3d7e2fe1f1b29e17b1cd914e"

[[files]]
file = "config/luckperms/translations/repository/ru_RU.properties"
hash = "10f4fe2028fefc01b436bd37b3d3dc1ebd231e86c234559f2f7cfcba61d80daf"

[[files]]
file = "config/luckperms/translations/repository/sk_SK.properties"
hash = "42162c5ec694fc09c55b1ded869a1eae7aa35d5a48f8952ed6f34635806c6573"

[[files]]
file = "config/luckperms/translations/repository/sr_CS.properties"
hash = "912c0aff4bb5bf77bf907c6ccb072fae19948311d8cb8f4f5d2f97c94adb5533"

[[files]]
file = "config/luckperms/translations/repository/status.json"
hash = "b5b7b1ed463d7ce9893ae789ed190c65b7a777f55b9a27d44db88bc51ed25b92"

[[files]]
file = "config/luckperms/translations/repository/sv_SE.properties"
hash = "4a0d1b26ef14040333044bfdec7ca6c32d81251c2f0d3b8006d409dac392f454"

[[files]]
file = "config/luckperms/translations/repository/tr_TR.properties"
hash = "7e089aa50240afd2674862bb7529265d050f00e3ac651e10b516e0931fb83f51"

[[files]]
file = "config/luckperms/translations/repository/uk_UA.properties"
hash = "1f9ecde9e332484f602bdba194fd46c8c400ee0997dc514f8e2b009bfca63a2b"

[[files]]
file = "config/luckperms/translations/repository/vi_VN.properties"
hash = "79c28807f8b0c5ade7aa50aa8ace0d4bc536ea21b605f45d0fa20daeec10955b"

[[files]]
file = "config/luckperms/translations/repository/zh_CN.properties"
hash = "749818ed7785e91888857d69c198f783d8d23a5d3853ed11d9e4faea41d3e538"

[[files]]
file = "config/luckperms/translations/repository/zh_TW.properties"
hash = "7d348067f10d8ca73262768709f30dde160f0fb1c72d2fe31076557fc9cec465"

[[files]]
file = "config/moderner_beta.json"
hash = "3a2360be7854a19786e99ff65d32e6f9a205cea96062718b304b566157088f9a"

[[files]]
file = "config/spark/config.json"
hash = "992ba9f3a4a7ce3de112eb95575328956fdc3ce6781c455ebce7b23db7e7da42"

[[files]]
file = "config/voicechat/translations.properties"
hash = "b258a94a5ed60fbf93b66c452c3d6e36b044f630741f90e5b13852a4805b235e"

[[files]]
file = "config/voicechat/voicechat-server.properties"
hash = "1b920776f11dabe9dedc9d75d068869f2cfb186740768063f383e54c774c4133"

[[files]]
file = "config/worldedit/worldedit.properties"
hash = "649ee572e5283466afca5999ebf7c5d25a148dfd6e3801d1d6d4c61b0c864dcf"

[[files]]
file = "mods/almanac.pw.toml"
hash = "eb0287bff177c7dfab5802e6dd6adcf966b8f97101cbe583834950b41fc2af93"
metafile = true

[[files]]
file = "mods/alternate-current.pw.toml"
hash = "fc8ffe66dc0c7eb55cf2ce38d1ae4bf1c4cdfbfdcda2636b1cd140c851e03cc5"
metafile = true

[[files]]
file = "mods/anti-xray.pw.toml"
hash = "7ffd2cbb973d987d543b36f12cc9362baae07b0983b83a8292f063ed4287f9a9"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
hash = "2d58b7783694c38d8264f263b9ee1f8b31c1aa9dd98866deb20719b252dc4b47"
metafile = true

[[files]]
file = "mods/bluemap-banners.pw.toml"
hash = "dd54576306bcdc7c078c493ab418a2b6253e1938a29dcda140fef4808a40420c"
metafile = true

[[files]]
file = "mods/bluemap.pw.toml"
hash = "853ba2ec022456ae2f357268a27c7cb1018b0c57e0c1e9071330f81e035f59f9"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "ff260b35492778bdce59ffa064a59c6a9953ffd409eb40782af14b78a29a2cb8"
metafile = true

[[files]]
file = "mods/chunky.pw.toml"
hash = "eaa52d6ff1bcb539956d50626085d9185eca346fabcf6b3c176c53192b9958ec"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "a06ef129798265e0d7249426fb0ed5c506725b0460dc3dfdb975b8978480895e"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
hash = "a5f67311e64ea67e8097c1fdd4d20cf11e1c5236334b5becabad7dabdae975db"
metafile = true

[[files]]
file = "mods/distanthorizons.pw.toml"
hash = "479cc9008a66ce4dea0b0be0f749a986d73f5fe778516d6682a5202e19706179"
metafile = true

[[files]]
file = "mods/easyauth.pw.toml"
hash = "4bad5720d383f38e68af1a423c66808a966845a362216548eba010608fa4e2fd"
metafile = true

[[files]]
file = "mods/elytra-lunge.pw.toml"
hash = "398630e0b309f368766d9c9730b1fb2f2a8711cf467a980b9a573b73b1a985bc"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "0229e8fe7f696f76a0fce46d11ddeb5d1f4b687f595558636abd27210cde2633"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "61afd7af5c645ffd966b2bd86be944eacd1e48a8044e8f67082225d4d9989f0c"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "76a12a836d4c7f0f943a1e391dd2d7b5c4673caa497fff16593d49449376b117"
metafile = true

[[files]]
file = "mods/forgiving-void.pw.toml"
hash = "b11daf574301e161180f0c44aa4f834bf0c0eedd11212334f7b060cbe5b4090d"
metafile = true

[[files]]
file = "mods/fuji.pw.toml"
hash = "35b3add9148b332b8200d4bd038bc4b756dd68db2dee27fa9dff567af3e2a43c"
metafile = true

[[files]]
file = "mods/image2map.pw.toml"
hash = "71915821f61cc0abc0920e331d41ce5d2ce5a6bd1edb9ec35d540e485f890a3a"
metafile = true

[[files]]
file = "mods/incendium.pw.toml"
hash = "bef0d78723bcf15335544a175244cb43416a58977e2b7551a7b5200a85af3bfa"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "0e87ab10adb3db84b1d6d2ce8bdd7158878b56c965055056b10ad6cde2634568"
metafile = true

[[files]]
file = "mods/lmd.pw.toml"
hash = "c921067d060d427e9295c8434d0ab1232566008caa300030b42c2ee2c12ad059"
metafile = true

[[files]]
file = "mods/luckperms.pw.toml"
hash = "0fcb21a2580ad82270c404aa36e042926a7f35b0151f785bd6c6afce23e6edc4"
metafile = true

[[files]]
file = "mods/maplink.pw.toml"
hash = "bb629dde390add8f98e58661320f3fe0bfd37f5f23e9cc0ce12b3786a4adc1f2"
metafile = true

[[files]]
file = "mods/moderner-beta.pw.toml"
hash = "7022fdce60750b3760cc13b4ecbc104e57ceda3996cede1528eb14eb5fa009df"
metafile = true

[[files]]
file = "mods/polymer.pw.toml"
hash = "b39ee5a28d5548d591e8f396d2407893affcc71470d7c058d3287039a960e55d"
metafile = true

[[files]]
file = "mods/recipecooldown.pw.toml"
hash = "43fbc9b70f49998be45314b9b557e925988825a204190be01ccbae5cc2df74df"
metafile = true

[[files]]
file = "mods/scalablelux.pw.toml"
hash = "936e9028071f4e49ecd551aadab4c161f9a7143764b4cc89f8077296bd8645a6"
metafile = true

[[files]]
file = "mods/seedguard.pw.toml"
hash = "d574929c48ee577c63e3dd7629b2f68a26f396d36af96306022edf793e4b7195"
metafile = true

[[files]]
file = "mods/servercore.pw.toml"
hash = "16a351dac4db6e5b8035f56090710a227d33482797ef5bcc09a367099304be74"
metafile = true

[[files]]
file = "mods/shifting-wares.pw.toml"
hash = "885b6cb2c46d2f8556fc814e577949c206aed617ab2aff7d9e5bdcdb9f3fd99b"
metafile = true

[[files]]
file = "mods/silk.pw.toml"
hash = "a4c742db2f87bd02aa5dfd47faab025d985a9e21e69c72dd923a643a7a908513"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "9ff1a261860fcb16a7c7f124d738abcdfc1297363412d237540685003ff04d6b"
metafile = true

[[files]]
file = "mods/skinrestorer.pw.toml"
hash = "779286fb8a1f7325f6ee888313506d65acc0504a6b9cfe0ed1075398048413d5"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
hash = "c073f13897a838e3c409e46b8a1d8cb510d6a6584dd815aeadaf4886f1779513"
metafile = true

[[files]]
file = "mods/tt20.pw.toml"
hash = "7390523148f7aa693093187cb9406bfe1a7b4c8d7afd0fe830b7a1aa0dd03040"
metafile = true

[[files]]
file = "mods/universal-graves.pw.toml"
hash = "c1166e4664aa67501d4daafac5e69cb29094dd46942d35e64b4d5d8a0a54decd"
metafile = true

[[files]]
file = "mods/veinminer-enchantment.pw.toml"
hash = "56d354ec654763cc6c6c1c81a0110a6267a28eb8beac6eecddca3810c4de2dbd"
metafile = true

[[files]]
file = "mods/veinminer.pw.toml"
hash = "fc7bfaa3cc133f968b1a4ee6f0635c2980fb277870aec45e9d68ff313b0d1d9d"
metafile = true

[[files]]
file = "mods/worldedit.pw.toml"
hash = "ec85eb2fb8af68643ac14c917ec83c0c9aae48fcce27d8ad9f9b76cfce9b7dea"
metafile = true

[[files]]
file = "mods/xaeronuhuh.pw.toml"
hash = "f9771f725cba1db2f87f3a78f204e9c7a2f2702abfc5681156af04d60e40a74d"
metafile = true
