name = "Ntxc Server"
author = "nelande"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "28da85d9cf65f9950b6848375e3ba72fb17a96d88bb8128af8b4d6e18482df25"

[versions]
fabric = "0.18.2"
minecraft = "1.21.11"
