name = "Ntxc Server"
author = "nelande"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d16c23e00283ea2bedd6dc5f41980df986b3cda943fb91fde47ac96cccd02414"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
