name = "Ntxc Server"
author = "nelande"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cb74b86f5df733d9a2f1f317d079677133bca906c556bdc766175773508b8b4a"

[versions]
fabric = "0.18.2"
minecraft = "1.21.11"
