name = "Ntxc Server"
author = "nelande"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b857a7faf81bdfd2176ebf9d261db1c6e9389773937366a3fcabe5bd9cc8c6a6"

[versions]
fabric = "0.18.2"
minecraft = "1.21.11"
