name = "Ntxc Server"
author = "nelande"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "723c887809e32feec2ab2c3531ea28982d265ccf81fda3ebe3144707482c7b6f"

[versions]
fabric = "0.18.2"
minecraft = "1.21.11"
