name = "Ntxc Server"
author = "nelande"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "632a092df7d2a86dd17f32a9e5d7d38c0ca99e97fda0add344d8d288ca4ed071"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
