name = "Ntxc Server"
author = "nelande"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d7c2c1d24a10cdc2febac51bd28ce0d0c15e365c0b93597d07996231c3b6ff29"

[versions]
fabric = "0.18.2"
minecraft = "1.21.11"
