name = "Ntxc Server"
author = "nelande"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "45ea6733637b0f1379c20c434d9529592dec847c857e857251ac1b53737d1187"

[versions]
fabric = "0.18.2"
minecraft = "1.21.11"
